name: "Nix"
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Install nix
      uses: cachix/install-nix-action@v20
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Setup cachix
      uses: cachix/cachix-action@v12
      with:
        name: nix-cargo-integration
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Test checks
      run: nix flake check -L --show-trace